#!/usr/bin/env node
// Regenerate src/app/icons.js from assets/icons/*.svg (app.md icons.js row).
// assets/icons is the source (retrieved from the Claude Design project —
// provenance in assets/icons/icons.md); the JS module exists so the icons
// inline into the single-file dist bundles.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets/icons');
const entries = readdirSync(dir).filter(f => f.endsWith('.svg')).sort()
  .map(f => {
    const svg = readFileSync(join(dir, f), 'utf8').trim();
    if (svg.includes('</script>') || svg.includes('`') || svg.includes('${')) {
      throw new Error(`${f}: unsafe content for template-literal embedding`);
    }
    return `  ${f.replace('.svg', '')}: \`${svg}\`,`;
  });

writeFileSync(join(root, 'src/app/icons.js'),
  `// GENERATED by scripts/icons.mjs from assets/icons/ — do not hand-edit.
// Weapon id → standalone inline SVG (app.md icons.js row; contract in
// test/icons.test.mjs). Upstream: the Claude Design project's weapon-icons
// template; see assets/icons/icons.md.
export const WEAPON_ICONS = {
${entries.join('\n')}
};
`);
console.log(`wrote src/app/icons.js (${entries.length} icons)`);
